on:
  push:
    branches: "**"
    tags-ignore: "*"

jobs:
  test-deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{matrix.deno-version}}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{matrix.deno-version}}
      - run: make
        env:
          CI: true
